### ISSUE TITLE
Build breaks: ImportError: cannot import name '__version__' from 'param._version'

### ISSUE THREAD

**Issue by yurivict** [holoviz/colorcet#119]
#### ALL software version info

Version: 3.0.1
Python-3.9
param-2.0.1
setuptools-63.1.0_1
FreeBSD 14.0

#### Description of expected behavior and the observed behavior
```
* Getting build dependencies for wheel...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/param/__init__.py", line 89, in <module>
    raise FileNotFoundError
FileNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/usr/local/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "/usr/local/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
    self.run_setup()
  File "/usr/local/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/usr/local/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 6, in <module>
    import pyct.build
  File "/usr/local/lib/python3.9/site-packages/pyct/__init__.py", line 1, in <module>
    import param
  File "/usr/local/lib/python3.9/site-packages/param/__init__.py", line 93, in <module>
    from ._version import __version__
ImportError: cannot import name '__version__' from 'param._version' (/usr/local/lib/python3.9/site-packages/param/_version.py)

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
*** Error code 1
```

#### Complete, minimal, self-contained example code that reproduces the issue
n/a - build breaks.

**Comment by maximlt** [comment]
This should have been fixed by https://github.com/holoviz/colorcet/pull/120
